name: Pull Request

on:
  push:
    branches:
      - feature/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          commit-message: Auto Pull Request
          title: Changes by ${{ github.ref }}
          branch: ${{ github.ref }} # The branch where you commit
          base: develop # Don't forget to specify the right base branch here
